# Generated by Django 4.1.7 on 2023-04-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_chat_participant_message'),
        ('user', '0003_rename_users_userfollower_following'),
    ]

    operations = [
    ]
