# Generated by Django 4.1.7 on 2023-04-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merge_20230401_1303'),
        ('user', '0004_message_is_read'),
    ]

    operations = [
    ]
