# Generated by Django 4.1.7 on 2023-04-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_is_online'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
