# Generated by Django 4.1.7 on 2023-03-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfilecontent',
            name='content_type',
        ),
        migrations.AddField(
            model_name='postfilecontent',
            name='type',
            field=models.CharField(choices=[('img', 'Img'), ('video', 'Video')], default='img', max_length=6),
        ),
    ]
